CREATE TABLE Clientes ( 
	id_cliente INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	cpf VARCHAR (17) UNIQUE NOT NULL, 	
	nome VARCHAR (50) NOT NULL,
	data_nascimento DATE NOT NULL,
	telefone VARCHAR (20) NOT NULL,
	email VARCHAR (70) NOT NULL
);

CREATE TABLE Medicamentos ( 
	id_medicamento INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nome VARCHAR (50) NOT NULL, 	
	fabricante VARCHAR (50) NOT NULL,
	principio_ativo VARCHAR (50) NOT NULL,
	data_validade DATE NOT NULL,
	preco DECIMAL (10,2) NOT NULL
);


